application: wilfriede
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /app/
  static_dir: app/

- url: /hyperspace/
  static_dir: hyperspace/

- url: /lens
  static_files: lens/index.html
  upload: lens/index.html

- url: /lens/
  static_dir: lens/

- url: /assets/
  static_dir: assets/

- url: /node_modules/
  static_dir: node_modules/

- url: /w/.*
  static_files: hyperspace/index.html
  upload: hyperspace/index.html

- url: (.*)/.*
  static_files: index.html
  upload: index.html