name: Wilfried Hounyo
description: My Website
avatar: https://avatars0.githubusercontent.com/u/1964213
disqus: wilfried
google_analytics: 
url: http://wilfried.me
baseurl: ""
markdown: kramdown
highlighter: pygments
permalink: story/:title/
paginate: 5
version: v3.0.0
sass:
  sass_dir: _scss
  style: :compressed
gems:
  - jemoji # Emoji please!
  - jekyll-paginate
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
